name: Skill Request
description: Request a new skill package
title: "feat(skills): "
labels: ["skill", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Request a new skill package for GitHub Copilot.
  
  - type: input
    id: skill-name
    attributes:
      label: Skill Name
      description: What should this skill be named?
      placeholder: e.g., "docker-compose-gen"
    validations:
      required: true
  
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: What problem does this skill solve?
      placeholder: Describe when and why this skill would be used
    validations:
      required: true
  
  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites
      description: What external tools or dependencies are needed?
      placeholder: List any required installations (e.g., ffmpeg, docker, jq)
    validations:
      required: false
  
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: What specific behaviors should this skill enable?
      placeholder: List the key capabilities or features needed
    validations:
      required: false
